homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_time_zone
  customize: !include customize.yaml

frontend:
  themes: !include themes.yaml
updater:
conversation:
discovery:
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.internet_time
      - sensor.time
      - sensor.time_date
      - sensor.time_utc
history:
sun:
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml

# Enables configuration UI
config:

http:
  #api_password: !secret ha_api_pass
  
  ###################### These three lines commented out to try to make reverse proxy work #############
  # base_url: https://gth758yha.ddns.net
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  
    ###################### Three lines below are for the reverse proxy #############
  base_url: https://homeassistant.gth758y.com
  use_x_forwarded_for: true
  trusted_proxies: 10.99.1.23

device_tracker: !include device_trackers.yaml

mqtt:
    broker: 10.99.1.23
    port: 1883
    username: !secret mmqtt_user
    password: !secret mmqtt_pass

# Enables a map showing the location of tracked devices
map:

# Text to speech
tts:
  - platform: google
  
cover: !include cover.yaml

# Cloud
#cloud:

group: !include groups.yaml
light: !include lights.yaml
automation: !include_dir_list automation
script: !include_dir_named scripts
zone: !include zones.yaml
zwave:
    usb_path: /dev/ttyACM0
    
recorder:
  purge_interval: 2
  purge_keep_days: 30
  db_url: !secret mariaDB_url

input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
scene: !include scenes.yaml

climate:
 platform: honeywell
 username: !secret honeywell_user
 password: !secret honeywell_pass
 region: us

notify:
  - platform: html5
    gcm_api_key: !secret gcm-server-key
    gcm_sender_id: !secret gcm-sender-id
    
# tesla:
  # username: !secret tesla_username
  # password: !secret tesla_pass

# vacuum:
  # - platform: roomba
    # host: 10.99.1.12
    # username: !secret roomba_user
    # password: !secret roomba_pass
    
circadian_lighting:
    latitude: 22
    longitude: -140
    min_colortemp: 2700
    

switch:
  - platform: circadian_lighting
    min_brightness: 70
    lights_ct:
      - light.living_room_short_lamp
      - light.living_room_shortest_lamp
      - light.living_room_tall_lamp
      - light.bedroom_tyler
      - light.bedroom_amy
      - light.bay_window
      - light.hallways
      - light.kitchen_overhead_1
      - light.kitchen_overhead_2
      - light.kitchen_overhead_3
      - light.kitchen_overhead_4
      - light.kitchen_overhead_5
      - light.kitchen_overhead_6
      - light.kitchen_overhead_7
      - light.kitchen_overhead_8
      - light.laundry_room_1
      - light.laundry_room_2
      
# switch:
  # - platform: circadian_lighting
    # min_brightness: 70
    # lights_ct:
      # - light.kitchen
      

      
system_health:

#ambient_station:
  #api_key: !secret pws_api_key
  #app_key: !secret pws_app_key
  
lovelace:
  mode: yaml