circadian_lighting:
    # latitude: 22
    # longitude: -140
    min_colortemp: 2700

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_time_zone
  customize: !include customize.yaml
  country: US

frontend:
  themes: !include themes.yaml
  # extra_module_url:
    # - /local/hass-bha-icons.js
# updater:
conversation:
# discovery:
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.internet_time
      - sensor.time
      - sensor.time_date
      - sensor.time_utc
history:
sun:
mobile_app:

lovelace:
  mode: yaml
  resources: !include lovelace/resources/resources.yaml
  
# camera: !include camera.yaml

# Enables configuration UI
config:

http:  
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.99.1.23
    - 172.16.0.0/12
 
# Enables a map showing the location of tracked devices
# map:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml
light: !include lights.yaml
automation: !include_dir_list automation
script: !include_dir_named scripts
zone: !include zones.yaml
    
recorder:
  # purge_interval: 2
  purge_keep_days: 30
  db_url: !secret mariaDB_url
  commit_interval: 30

input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
input_text: !include input_text.yaml
scene: !include scenes.yaml
# cover: !include cover.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
mqtt: !include mqtt.yaml



switch:
  - platform: circadian_lighting
    min_brightness: 70
    lights_ct:
      - light.bay_window
      # - light.hallways
      - light.kitchen
      # - light.laundry_room
      - light.living_room
      - light.loft
      - light.guest_room
      - light.office      

  - platform: circadian_lighting
    min_brightness: 70
    name: guest_hallways
    lights_ct:
      - light.hallways
      
  - platform: circadian_lighting
    min_brightness: 70
    name: master_bedroom
    lights_ct:
      - light.bedroom_tyler
      - light.bedroom_amy

      
  - platform: circadian_lighting
    min_brightness: 70
    name: laundry_room
    lights_ct:
      - light.laundry_room
      
  - platform: circadian_lighting
    min_brightness: 70
    name: open_areas
    lights_ct:
      - light.foyer
      - light.breakfast_area
      - light.office_hallway_1
      - light.office_hallway_2
      

      
system_health:


