circadian_lighting:
    # latitude: 22
    # longitude: -140
    min_colortemp: 2700

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_time_zone
  customize: !include customize.yaml

frontend:
  themes: !include themes.yaml
  # extra_module_url:
    # - /local/hass-bha-icons.js
# updater:
conversation:
discovery:
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.internet_time
      - sensor.time
      - sensor.time_date
      - sensor.time_utc
history:
sun:
mobile_app:
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
# mqtt: !include mqtt.yaml

lovelace:
  mode: yaml
  resources: !include lovelace/resources/resources.yaml
  
# camera: !include camera.yaml

# Enables configuration UI
config:

http:  
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.99.1.23
    - 172.16.0.0/12

#device_tracker: !include device_trackers.yaml

mqtt:
  broker: 10.99.1.23
  port: 1883
  username: !secret mmqtt_user
  password: !secret mmqtt_pass
    
  # sensor:
    # # Sensor for monitoring the bridge state
    # - name: Bridge state
      # unique_id: zigbee2mqtt_bridge_state_sensor
      # state_topic: "zigbee2mqtt/bridge/state"
      # value_template: "{{ value_json.state }}"
      # icon: mdi:router-wireless
      # entity_category: diagnostic
      # device:
        # identifiers: zigbee2mqtt
        # name: "Zigbee2MQTT"
        # model: "Zigbee2MQTT"
        # manufacturer: "Zigbee2MQTT"  
    # # Sensor for Showing the Zigbee2MQTT Version
    # - name: Version
      # unique_id: zigbee2mqtt_version_sensor
      # state_topic: "zigbee2mqtt/bridge/info"
      # value_template: "{{ value_json.version }}"
      # icon: mdi:zigbee
      # entity_category: diagnostic
      # device:
        # identifiers: zigbee2mqtt
        # name: "Zigbee2MQTT"
        # model: "Zigbee2MQTT"
        # manufacturer: "Zigbee2MQTT"  
    # # Sensor for Showing the Coordinator Version
    # - name: Coordinator Version
      # unique_id: zigbee2mqtt_coordinator_version_sensor
      # state_topic: "zigbee2mqtt/bridge/info"
      # value_template: "{{ value_json.coordinator.meta.revision }}"
      # icon: mdi:chip
      # entity_category: diagnostic
      # device:
        # identifiers: zigbee2mqtt
        # name: "Zigbee2MQTT"
        # model: "Zigbee2MQTT"
        # manufacturer: "Zigbee2MQTT"  
    # - name: Networkmap
      # unique_id: zigbee2mqtt_networkmap_sensor
      # # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
      # state_topic: zigbee2mqtt/bridge/response/networkmap
      # value_template: >-
        # {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
      # # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
      # json_attributes_topic: zigbee2mqtt/bridge/response/networkmap
      # json_attributes_template: "{{ value_json.data.value | tojson }}"
      # entity_category: diagnostic
      # device:
        # identifiers: zigbee2mqtt
        # name: "Zigbee2MQTT"
        # model: "Zigbee2MQTT"
        # manufacturer: "Zigbee2MQTT"

# Enables a map showing the location of tracked devices
map:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
  
cover: !include cover.yaml


group: !include groups.yaml
light: !include lights.yaml
automation: !include_dir_list automation
script: !include_dir_named scripts
zone: !include zones.yaml
# zwave:
    # usb_path: /dev/ttyACM0
    # network_key: !secret zwave_key
    
recorder:
  # purge_interval: 2
  purge_keep_days: 30
  db_url: !secret mariaDB_url
  commit_interval: 30

input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
input_text: !include input_text.yaml
scene: !include scenes.yaml

# timer:
  # zigbee_permit_join:
    # name: Time remaining
    # duration: 254



switch:
  - platform: circadian_lighting
    min_brightness: 70
    lights_ct:
      - light.bay_window
      # - light.hallways
      - light.kitchen
      # - light.laundry_room
      - light.living_room
      - light.loft
      - light.guest_room
      - light.office      

  - platform: circadian_lighting
    min_brightness: 70
    name: guest_hallways
    lights_ct:
      - light.hallways
      
  - platform: circadian_lighting
    min_brightness: 70
    name: master_bedroom
    lights_ct:
      - light.bedroom_tyler
      - light.bedroom_amy

      
  - platform: circadian_lighting
    min_brightness: 70
    name: laundry_room
    lights_ct:
      - light.laundry_room
      
  - platform: circadian_lighting
    min_brightness: 70
    name: open_areas
    lights_ct:
      - light.foyer
      - light.breakfast_area
      - light.office_hallway_1
      - light.office_hallway_2
      
# switch:
  # - name: "Main join"
    # unique_id: zigbee2mqtt_main_join_switch
    # state_topic: "zigbee2mqtt/bridge/info"
    # value_template: '{{ value_json.permit_join | lower }}'
    # command_topic: "zigbee2mqtt/bridge/request/permit_join"
    # payload_on: "true"
    # payload_off: "false"
    # device:
      # identifiers: zigbee2mqtt
      # name: "Zigbee2MQTT"
      # model: "Zigbee2MQTT"
      # manufacturer: "Zigbee2MQTT"

      
system_health:

# octoprint:
  # host: 10.99.1.70
  # api_key: !secret octo_api_key

# babybuddy:
  # address: https://10.99.1.23
  # port: 8000
  # path: ""
  # api_key: !secret babybuddy_api_key
