homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_time_zone
  customize: !include customize.yaml

frontend:
updater:
conversation:
discovery:
logbook:
history:
sun:
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml

# Enables configuration UI
config:

http:
  api_password: !secret ha_api_pass
  base_url: https://gth758yha.ddns.net
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

device_tracker: !include device_trackers.yaml

mqtt:
    broker: core-mosquitto
    username: !secret mmqtt_user
    password: !secret mmqtt_pass

# Enables a map showing the location of tracked devices
map:

# Text to speech
tts:
  - platform: google
  
cover: !include cover.yaml

# Cloud
#cloud:

group: !include groups.yaml
automation: !include_dir_list automation
script: !include_dir_named scripts
zone: !include zones.yaml
zwave:
    usb_path: /dev/ttyACM0
    
recorder:
  purge_interval: 2
  purge_keep_days: 30
  db_url: !secret mariaDB_url

input_select: !include input_select.yaml
scene: !include scenes.yaml

climate:
 platform: honeywell
 username: !secret honeywell_user
 password: !secret honeywell_pass
 region: us

notify:
  - platform: html5
    gcm_api_key: !secret gcm-server-key
    gcm_sender_id: !secret gcm-sender-id
    
tesla:
  username: !secret tesla_username
  password: !secret tesla_pass

vacuum:
  - platform: roomba
    host: 10.99.1.140
    username: !secret roomba_user
    password: !secret roomba_pass