title: Home
# resources:
  # - url: /local/custom-lovelace/card-tools.js?v=1
    # type: js
  # - url: /local/custom-lovelace/layout-card.js?v=1
    # type: js
  # - url: /local/custom-lovelace/popup-card.js?v=1
    # type: js
  # - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v.1
    # type: module
  # - url: /local/custom-lovelace/mini-graph-card-bundle.js?v=0.3.2
    # type: module
  # - url: /local/custom-lovelace/monster-card.js?v=1
    # type: js
  # - url: /local/custom-lovelace/bar-card.js?v=2
    # type: js
    
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/10_lights_view.yaml
  - !include lovelace/20_sensors_view.yaml
  - !include lovelace/30_automations_view.yaml
  - !include lovelace/40_weather_view.yaml
  - !include lovelace/50_ip_cams_view.yaml
  - !include lovelace/60_traffic_view.yaml
  - !include lovelace/70_3d_printer_view.yaml
  - !include lovelace/80_swim-bike-run.yaml
  - !include lovelace/90_halloween.yaml
