alias: 3D Print Started
trigger:
  platform: state
  entity_id: binary_sensor.octoprint_printing
  from: 'off'
  to: 'on'

action:
  - service: light.turn_on
    data:
      entity_id: light.3d_printer
    # data_template:
      # xy_color: "{{ states.sensor.circadian_values.attributes.xy_color }}"