# turns off circadian lights when it reaches 0%

alias: Turn off circadian lights
trigger:
    platform: template
    value_template: >-
          {% set hour = states('sensor.time').split(':')[0]|int %}
          {{ (states('sensor.circadian_values') | float < 0)
             and (hour > 19) }}

action:
  - service: switch.turn_off
    data:
      entity_id: switch.circadian_lighting_circadian_lighting
      
  - service: script.loft_sunset_sim