# turns on circadian lights

alias: Turn on circadian lights
trigger:
  platform: state
  entity_id: binary_sensor.trigger_circ_lights
  from: 'off'
  to: 'on'

action:
  - service: switch.turn_on
    data:
      entity_id: switch.circadian_lighting_circadian_lighting
      
  - service: switch.turn_on
    data:
      entity_id: switch.circadian_lighting_master_bedroom
      
  - service: switch.turn_on
    data:
      entity_id: switch.circadian_lighting_open_areas