alias: Not at Home - Garage Door Open
trigger:
  platform: state
  entity_id: binary_sensor.garage_open
  to: 'on'
condition:
  condition: state
  entity_id: binary_sensor.anybody_home
  state: 'off'
action:
  - delay: '00:03:00'
  - condition: state
    entity_id: binary_sensor.anybody_home
    state: 'off'
    for:
      seconds: 180
  - service: notify.notify
    data_template:
      message: "Garage opened and you're not home!"