alias: Bedtime Shutdown Routine
trigger: 
    platform: state
    entity_id: binary_sensor.house_asleep
    from: 'off'
    to: 'on'
action:
  - service: script.check_garage_doors
  - delay: '00:00:02'
  - service: script.nighttime_shutdown