alias: Interior Lights On
trigger: 
    platform: state
    entity_id: binary_sensor.is_it_dark
    from: 'off'
    to: 'on'
condition:
  condition: state
  entity_id: binary_sensor.house_asleep
  state: 'off'
action:
  - service: scene.turn_on
    entity_id: scene.living_room_normal
  - service: scene.turn_on
    entity_id: scene.master_bedroom_on
  # - service: scene.turn_on
    # entity_id: scene.guest_bedroom_on
  # - service: scene.turn_on
    # entity_id: scene.kitchen_on
  - service: scene.turn_on
    entity_id: scene.under_bed_blue
  - service: scene.turn_on
    entity_id: scene.exterior_lights_on
