alias: It's really light out
trigger:
    platform: state
    entity_id: binary_sensor.is_it_kind_of_dark
    from: 'on'
    to: 'off'
action:
  - service: scene.turn_on
    data:
      entity_id: scene.living_room_off
