alias: Kitchen on - Evening
trigger:
  platform: state
  entity_id: binary_sensor.kitchen_motion_delay
  to: 'on'
condition:
  - condition: state
    entity_id: sensor.time_of_day
    state: 'Evening'
action:
  - service: light.turn_on
    entity_id: 
      - light.kitchen
    data:
      color_temp: 443  # Matches the settings from the scene
      brightness: 145
      transition: 1