
alias: Kitchen on for Motion Daytime
trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_delay
    to: 'on'
condition:
  - condition: state
    entity_id: switch.circadian_lighting_circadian_lighting
    state: 'on'
action:
  - service: scene.turn_on
    data:
      entity_id: scene.kitchen_on