alias: Living Room Lights on Early
trigger:
    platform: template
    value_template: >-
          {{ is_state('binary_sensor.is_it_kind_of_dark', 'on')
             and is_state('binary_sensor.anybody_home', 'on') }}
condition:
  condition: state
  entity_id: binary_sensor.house_asleep
  state: 'off'
action:
  - service: scene.turn_on
    entity_id: scene.living_room_normal