# turns on the basement lights for porch motion or zwift (or random possums/racoons probably)

alias: Turn on basement lights
trigger:
    platform: template
    value_template: >-
          {{ (is_state('binary_sensor.back_porch_motion_delay', 'on') or is_state('binary_sensor.anybody_on_zwift_delay', 'on')) and is_state('binary_sensor.is_it_kind_of_dark', 'on') }}

action:
  - service: scene.turn_on
    data:
      entity_id: scene.basement_path_and_entrance_on