alias: TV on - Denon On
trigger:
    platform: state
    entity_id:  media_player.un55js9000
    to: 'on'
condition:
  condition: state
  entity_id: media_player.denon_avr_x2000
  state: 'off'
action:
  - service: media_player.turn_on
    entity_id: media_player.denon_avr_x2000
