alias: TV on - Bias Lights On
trigger:
    platform: state
    entity_id:  media_player.un55js9000
    to: 'on'
condition:
  condition: state
  entity_id: binary_sensor.anybody_home
  state: 'on'
action:
  - service: scene.turn_on
    entity_id: scene.tv_bias_lights_to_6500K
