alias: TV off - Denon Off
trigger:
    platform: state
    entity_id:  media_player.lg_webos_smart_tv
    from: 'on'
    for:
        seconds: 2

action:
  - service: media_player.turn_off
    entity_id: media_player.denon_avr_x3800h
