alias: TV on - Bias Lights On
trigger:
  platform: state
  entity_id: media_player.lg_webos_smart_tv
  to: 'on'
condition:
  condition: state
  entity_id: binary_sensor.anybody_home
  state: 'on'
action:
  - service: light.turn_on
    entity_id: light.television
    data:
      color_temp: 154
      brightness: 255
      transition: 2