alias: TV on - Denon On
trigger:
    platform: state
    entity_id:  media_player.lg_webos_smart_tv
    to: 'on'
condition:
  condition: state
  entity_id: media_player.denon_avr_x3800h
  state: 'off'
action:
  - service: media_player.turn_on
    entity_id: media_player.denon_avr_x3800h
