alias: TV on - Bias Lights On
trigger:
    platform: state
    entity_id:  media_player.samsung_living_room_tv
    to: 'off'
    for:
        seconds: 10

action:
  - service: scene.turn_on
    entity_id: scene.tv_bias_lights_off
