alias: TV off - Bias Lights Off
trigger:
    platform: state
    entity_id:  media_player.lg_webos_smart_tv
    from: 'on'
    for:
        seconds: 10

action:
  - service: scene.turn_on
    entity_id: scene.tv_bias_lights_off
