alias: Underbed - Amy On While Sleeping
trigger:
    platform: state
    entity_id: binary_sensor.amy_out_of_bed_while_asleep
    to: 'on'
    
condition:
    condition: state
    entity_id: binary_sensor.amy_home
    state: 'on'
    
action:
  - service: scene.turn_on
    data:
      entity_id: scene.amy_underbed_nightlight