alias: Underbed - Tyler On While Sleeping
trigger:
  platform: state
  entity_id: binary_sensor.tyler_out_of_bed_while_asleep
  to: 'on'
condition:
  condition: state
  entity_id: binary_sensor.tyler_home
  state: 'on'
action:
  - service: light.turn_on
    entity_id: light.wled_underbed
    data:
      xy_color: [0.7, 0.3]  # Adjust to match your desired color
      brightness: 64
      transition: 2