alias: Wake Up
trigger:
    platform: state
    entity_id: binary_sensor.house_asleep
    from: 'on'
    to: 'off'
condition:
  condition: state
  entity_id: binary_sensor.anybody_home
  state: 'on'
action:
  - service: media_player.media_stop
    data:
      entity_id: media_player.living_room_speaker_2
