alias: Wake Up
trigger:
    platform: template
    value_template: >-
          {{ (is_state('input_select.tyler_status', 'alarming') and is_state('binary_sensor.tyler_home', 'on'))
             or (is_state('input_select.amy_status', 'alarming') and is_state('binary_sensor.amy_home', 'on')) }}
action:
  - service: script.turn_on
    data:
      entity_id: script.sunrise_simulation
