alias: Wake Up
trigger:
    platform: template
    value_template: >-
          {{ is_state('input_select.tyler_status', 'alarming')
             or is_state('input_select.amy_status', 'alarming') }}
condition:
  condition: state
  entity_id: binary_sensor.anybody_home
  state: 'on'
action:
  - service: script.turn_on
    data:
      entity_id: script.sunrise_simulation
